version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 7
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 7
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
