plugins:
  "@textlint/markdown":
    extensions:
      - ".mdx"
rules:
  preset-ja-technical-writing:
    sentence-length:
      max: 140
    max-comma:
      max: 5
    no-exclamation-question-mark: false
  preset-ja-spacing: true
  prh:
    rulePaths:
      - ".textlint-prh/WEB+DB_PRESS.yml"
      - ".textlint-prh/kenchan0130.yml"
  no-nfd: true
filters:
  comments: true
