# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-minifier

# Google analytics
ga_tracking_id: "UA-79827366-2"

jekyll-minifier:
  exclude: '*.xml'
