# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap

# Google analytics
ga_tracking_id: "UA-79827366-2"
