exclude:
  - '/vendor/'
  - '/node_modules/'
  - '/scripts/'
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - '/webpack/'
  - tsconfig.json
  - '*.config.js'
  - LISENCE.md
  - README.md
  - .jekyll-cache
  - .sass-cache

# Development
livereload: true

# Site settings
title: 'kenchan0130 blog'
subtitle: "A web Developer's blog"
email:
name: Tadayuki Onishi
description: >
  Web エンジニア。記録に残したいことを雑に備忘するブログ。
  投稿内容は個人の見解であり所属する組織の公式見解ではありません。
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://kenchan0130.github.io' # the base hostname & protocol for your site
cover: '/assets/header_image.jpg'
logo: '/assets/logo.png'
profile_images:
  - '/assets/profile_critical_pass.png'
  - '/assets/profile_hi.png'
  - '/assets/profile_standard.png'

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/page:num/'
inter_post_navigation: false
highlighter: rouge

kramdown:
  toc_levels: 1..3
  syntax_highlighting: rouge

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

collections:
  pages:
    output: true
  posts:
    output: true
  legacy:
    output: true

defaults:
  - scope:
      path: '_posts/post'
      type: 'posts'
    values:
      layout: post
      permalink: /:path
  - scope:
      path: ''
      type: 'legacy'
    values:
      layout: redirect
      permalink: /:categories/:year/:month/:day/:title:output_ext

autoprefixer:
  browsers:
    - last 2 versions

# Disqus comments
# disqus_shortname: bencentra

# Category descriptions (for archive pages)
descriptions:
  - cat: system-administration
    desc: ''

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: kenchan0130
    url: https://twitter.com/kenchan0130
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username:
    url:
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: kenchan0130
    url: https://github.com/kenchan0130
    desc: Fork me on GitHub
    share: false

  - name: Hatena
    icon: hatena
    username:
    url:
    desc: Share to Hatena Bookmark
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
  og_image: '/assets/logo.png'
  og_image_type: 'image/png'

  os_repo: 'https://github.com/kenchan0130/kenchan0130.github.io'
  os_rcs_type: 'git'
  os_src: 'git@github.com:kenchan0130/kenchan0130.github.io.git'

lazy_load_image:
  src_attr_name: data-src
  preload_image: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
  class_attr_values:
    - lazyload
