version: 2.1

executors:
  jekyll:
    working_directory: ~/kenchan0130.github.io
    docker:
      - image: circleci/ruby:2.6-node
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          JEKYLL_BUILD_DESTINATION_PATH: _site
          JEKYLL_ENV: production
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          LANG: ja_JP.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: ja_JP.UTF-8
          GIT_USERNAME: "kenchan0130 by CI"
          GIT_EMAIL: "<>"

commands:
  setup-infra:
    steps:
      - run:
          name: Update the list of installable packages
          command: sudo apt-get update

      - run:
          name: Install libcurl4-openssl-dev
          command: sudo apt-get install -y libcurl4-openssl-dev

  ruby-dependencies:
    steps:
      - run:
          name: Update bundler
          command: gem update bundler

      - restore_cache:
          keys:
            - v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-ruby-dependencies-

      - run:
          name: Install ruby dependencies
          command: bundle check || bundle install

      - save_cache:
          key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  node-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-

      - run:
          name: Install node dependencies
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - node_modules/
            - ~/.cache/yarn
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor:
      name: jekyll
    steps:
      - checkout
      - setup-infra
      - ruby-dependencies
      - node-dependencies

      - run:
          name: YAML Style Check
          command: bundle exec rake yamllint

      - run:
          name: RuboCop Style Check
          command: bundle exec rubocop

      - run:
          name: Text Style Check
          command: yarn lint:run

      - run:
          name: Build Jekyll
          command: yarn build && bundle exec jekyll build --verbose --trace --config "_config.yml,_config_production.yml" --destination ${JEKYLL_BUILD_DESTINATION_PATH}

      - run:
          name: Test for generated HTML
          command: bundle exec rake htmlproofer:without_external_link[${JEKYLL_BUILD_DESTINATION_PATH}]

      - run:
          name: Deploy development branch to master
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              git config --global user.name "${GIT_USERNAME}"
              git config --global user.email "${GIT_EMAIL}"
              bundle exec rake deploy --trace
            fi

  check-external-link:
    executor:
      name: jekyll
    steps:
      - checkout
      - setup-infra
      - ruby-dependencies
      - node-dependencies

      - run:
          name: Build Jekyll
          command: yarn build && bundle exec jekyll build --verbose --trace --config "_config.yml,_config_production.yml" --destination ${JEKYLL_BUILD_DESTINATION_PATH}

      - run:
          name: Check external links for generated HTML
          command: bundle exec rake htmlproofer:with_external_link[${JEKYLL_BUILD_DESTINATION_PATH}]

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  nightly-workflow:
    triggers:
      - schedule:
          cron: "00 00 * * *" # UTC (JST +9)
          filters:
            branches:
              only:
                - development
    jobs:
      - check-external-link
