version: 2

jobs:
  build:
    working_directory: ~/kenchan0130.github.io
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          JEKYLL_BUILD_DESTINATION_PATH: _site
          JEKYLL_ENV: production
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          LANG: ja_JP.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: ja_JP.UTF-8

    steps:
      - checkout

      # Ruby dependencies
      - restore_cache:
          keys:
            - v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-ruby-dependencies-
          paths:
            - vendor/bundle

      - run:
          name: Install ruby dependencies
          command: bundle install

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
      # Ruby dependencies end

      # Node dependencies
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-
          paths:
            - node_modules

      - run:
          name: Install node dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
      # Node dependencies end

      - run:
          name: YAML Style Check
          command: bundle exec rake yamllint

      - run:
          name: RuboCop Style Check
          command: bundle exec rubocop

      - run:
          name: Optimize images
          command: yarn run imagemin

      - run:
          name: Build Jekyll
          command: bundle exec jekyll build --verbose --config "_config.yml,_config_production.yml" --destination $JEKYLL_BUILD_DESTINATION_PATH

      - run:
          name: Test for generated HTML
          command: bundle exec htmlproofer $JEKYLL_BUILD_DESTINATION_PATH --check-html --disable-external

      - deploy:
          name: Deploy development branch to master
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              git config --global user.name "kenchan0130 by CI"
              git config --global user.email "<>"
              bundle exec rake deploy --trace
            fi
