name: CI
on:
  pull_request:

env:
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3
  BUNDLE_PATH: vendor/bundle
  JEKYLL_BUILD_DESTINATION_PATH: _site
  JEKYLL_ENV: production
  TZ: '/usr/share/zoneinfo/Asia/Tokyo'
  LANG: ja_JP.UTF-8
  LC_ALL: C.UTF-8
  LANGUAGE: ja_JP.UTF-8

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install ruby gems
        run: |
          bundle check || bundle install
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install Node.js packages
        run: |
          yarn install --pure-lockfile
      - name: Run linters
        run: |
          bundle exec rake yamllint
          bundle exec rubocop
          yarn lint:run

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install ruby gems
        run: |
          bundle check || bundle install
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install Node.js packages
        run: |
          yarn install --pure-lockfile
      - name: Build Jekyll
        run: |
          yarn build
          bundle exec jekyll build --verbose --trace --config "_config.yml,_config_production.yml" --destination "${JEKYLL_BUILD_DESTINATION_PATH}"
      - name: Check generated HTML files
        run: |
          bundle exec rake htmlproofer:without_external_link["${JEKYLL_BUILD_DESTINATION_PATH}"]
