name: Indexing
on:
  workflow_dispatch:
  push:
    branches:
      - development

env:
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3
  BUNDLE_PATH: vendor/bundle
  JEKYLL_BUILD_DESTINATION_PATH: _site
  JEKYLL_ENV: production
  TZ: '/usr/share/zoneinfo/Asia/Tokyo'
  LANG: ja_JP.UTF-8
  LC_ALL: C.UTF-8
  LANGUAGE: ja_JP.UTF-8
  cache-version: v1

jobs:
  skip-indexing:
    runs-on: ubuntu-latest
    outputs:
      is_skip: ${{ steps.set_is_skip.outputs.is_skip }}
    steps:
      - uses: actions/checkout@v2
      - name: Set is_skip
        id: set_is_skip
        run: |
          IS_SKIP=$(git diff --name-only ${GITHUB_SHA} $(curl "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/commits?sha=development" | jq -r .[1].sha) | grep -E "^_posts/.*$" && echo false || echo true)
          echo "::set-output name=is_skip::${IS_SKIP}"
      - run: echo "[skip] ${{ steps.set_is_skip.outputs.is_skip }}"

  indexing:
    runs-on: ubuntu-latest
    needs: skip-indexing
    if: ${{ ! needs.skip-indexing.outputs.is_skip }}
    steps:
      - uses: actions/checkout@v2
      - name: Get a version of .ruby-version
        run: echo "::set-output name=ruby-version::$(cat .ruby-version)"
        id: rbenv
      - name: Setup Ruby ${{ steps.rbenv.outputs.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.rbenv.outputs.ruby-version }}
      - name: Save Ruby gems cache
        uses: actions/cache@v2
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: ${{ env.cache-version }}-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-gems-
      - name: Install ruby gems
        run: |
          bundle check || bundle install
      - name: Create algolia indexing
        run: |
          ./scripts/indexing.sh
        env:
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
